name: Use Docker Image

on:
  push:

jobs:
  run:
    runs-on: ubuntu-22.04
    container: ockawin/v1-svc-nginx-php:8.1-3.17-development-amd64
    steps:
      - name: Checkout repository
        run: git clone --depth 1 "https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" .
      - run: echo "Hello, World!"
      - run: cat README.md